print("################################")
print("#                              #")
print("#    Nazril Hafiz Rasyidin     #")
print("#        2610817110005         #")
print("#                              #")
print("################################")